version: '3.8'

services:
  support-units:
    image: support-units:dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: support-units
    restart: unless-stopped
    ports:
      - 0.0.0.0:3001:3001
    volumes:
      - ./:/app

  mysql:
    container_name: mysql
    image: mysql:8.0.32
    restart: unless-stopped
    environment:
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=mysql
    ports:
      - 0.0.0.0:3306:3306
    volumes:
      - ./system/mysql:/var/lib/mysql
    command:
      [
        'mysqld',
        '--character-set-server=utf8',
        '--collation-server=utf8_general_ci'
      ]
